export const STOCK_REFERENCE_SOURCE = "Laporan SO Agustus.xlsx";
export const STOCK_REFERENCE_ITEMS = [
  {
    "id": "milktea-powder",
    "name": "Milktea Powder",
    "unit": "Bags",
    "cartonSize": 10,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 41.0,
    "lastPrimaryQty": 20.0,
    "lastSecondaryQty": 21.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": true,
    "criticalThreshold": 10,
    "lowThreshold": 20,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "ice-cream-yoghurt",
    "name": "Ice Cream Yoghurt",
    "unit": "Bags",
    "cartonSize": 8,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 14.0,
    "lastPrimaryQty": 11.0,
    "lastSecondaryQty": 3.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": true,
    "criticalThreshold": 8,
    "lowThreshold": 16,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 8,
    "active": true
  },
  {
    "id": "ice-cream-original",
    "name": "Ice Cream Original",
    "unit": "Bags",
    "cartonSize": 8,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 5.0,
    "lastPrimaryQty": 2.0,
    "lastSecondaryQty": 3.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 2,
    "lowThreshold": 6,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 2,
    "active": true
  },
  {
    "id": "peach-flavor-oolong-tea",
    "name": "Peach Flavor Oolong Tea",
    "unit": "Bags",
    "cartonSize": 200,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 136.0,
    "lastPrimaryQty": 136.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "black-tea-putih",
    "name": "Black Tea Putih",
    "unit": "Pack",
    "cartonSize": 8,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 1.0,
    "lastPrimaryQty": 1.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 2,
    "lowThreshold": 6,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 2,
    "active": true
  },
  {
    "id": "black-tea",
    "name": "Black Tea",
    "unit": "Pack",
    "cartonSize": 200,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 205.0,
    "lastPrimaryQty": 205.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "jasmine-green-tea-blooming",
    "name": "Jasmine Green Tea / Blooming",
    "unit": "Bags",
    "cartonSize": 60,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 99.0,
    "lastPrimaryQty": 60.0,
    "lastSecondaryQty": 39.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 15,
    "lowThreshold": 45,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 15,
    "active": true
  },
  {
    "id": "green-tea",
    "name": "Green Tea",
    "unit": "Bags",
    "cartonSize": 200,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 0.0,
    "lastPrimaryQty": 0.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "green-tea-kemasan-hijau",
    "name": "Green Tea Kemasan Hijau",
    "unit": "Bags",
    "cartonSize": 50,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 14.0,
    "lastPrimaryQty": 13.0,
    "lastSecondaryQty": 1.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 12,
    "lowThreshold": 38,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 12,
    "active": true
  },
  {
    "id": "da-hong-pao-tea",
    "name": "Da Hong Pao Tea",
    "unit": "Bags",
    "cartonSize": 200,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 298.0,
    "lastPrimaryQty": 200.0,
    "lastSecondaryQty": 98.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "lemon-powder",
    "name": "Lemon Powder",
    "unit": "Bags",
    "cartonSize": 2,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Kitchen",
    "category": "Fresh",
    "currentQty": 1.0,
    "lastPrimaryQty": 1.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 1,
    "lowThreshold": 3,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 1,
    "active": true
  },
  {
    "id": "sugar-syrup",
    "name": "Sugar Syrup",
    "unit": "Barels",
    "cartonSize": 4,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 56.0,
    "lastPrimaryQty": 48.0,
    "lastSecondaryQty": 8.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": true,
    "criticalThreshold": 5,
    "lowThreshold": 10,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 5,
    "active": true
  },
  {
    "id": "ice-cream-corn",
    "name": "Ice Cream Corn",
    "unit": "PCS",
    "cartonSize": 400,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Packaging",
    "currentQty": 1773.0,
    "lastPrimaryQty": 1600.0,
    "lastSecondaryQty": 173.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 40,
    "lowThreshold": 120,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 40,
    "active": true
  },
  {
    "id": "tapioca-pearl-boba",
    "name": "Tapioca Pearl/Boba",
    "unit": "Bags",
    "cartonSize": 16,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 20.0,
    "lastPrimaryQty": 16.0,
    "lastSecondaryQty": 4.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 4,
    "lowThreshold": 12,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 4,
    "active": true
  },
  {
    "id": "popping-boba",
    "name": "Popping Boba",
    "unit": "PCS",
    "cartonSize": 12,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 9.0,
    "lastPrimaryQty": 9.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 25,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "coffe-powder",
    "name": "Coffe Powder",
    "unit": "Bags",
    "cartonSize": 20,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 17.0,
    "lastPrimaryQty": 17.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 5,
    "lowThreshold": 15,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 5,
    "active": true
  },
  {
    "id": "caramel-pudding",
    "name": "Caramel Pudding",
    "unit": "Bags",
    "cartonSize": 20,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 9.0,
    "lastPrimaryQty": 9.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 5,
    "lowThreshold": 15,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 5,
    "active": true
  },
  {
    "id": "jelly-powder",
    "name": "Jelly Powder",
    "unit": "Bags",
    "cartonSize": 8,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 10.0,
    "lastPrimaryQty": 8.0,
    "lastSecondaryQty": 2.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 2,
    "lowThreshold": 6,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 2,
    "active": true
  },
  {
    "id": "taffe-syrup",
    "name": "Taffe Syrup",
    "unit": "Barels",
    "cartonSize": 8,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 8.0,
    "lastPrimaryQty": 8.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 2,
    "lowThreshold": 6,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 2,
    "active": true
  },
  {
    "id": "cookies-crumble",
    "name": "Cookies Crumble",
    "unit": "Bags",
    "cartonSize": 24,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 10.0,
    "lastPrimaryQty": 10.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 6,
    "lowThreshold": 18,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 6,
    "active": true
  },
  {
    "id": "nata-de-coco-coconut-jelly",
    "name": "Nata De Coco/Coconut Jelly",
    "unit": "Bags",
    "cartonSize": 9,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 18.0,
    "lastPrimaryQty": 9.0,
    "lastSecondaryQty": 9.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 2,
    "lowThreshold": 7,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 2,
    "active": true
  },
  {
    "id": "peach-jam",
    "name": "Peach Jam",
    "unit": "Bags",
    "cartonSize": 16,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 11.0,
    "lastPrimaryQty": 11.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 4,
    "lowThreshold": 12,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 4,
    "active": true
  },
  {
    "id": "strawberry-jam",
    "name": "Strawberry Jam",
    "unit": "Bags",
    "cartonSize": 16,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 11.0,
    "lastPrimaryQty": 11.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 4,
    "lowThreshold": 12,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 4,
    "active": true
  },
  {
    "id": "manggo-jam",
    "name": "Manggo Jam",
    "unit": "Bags",
    "cartonSize": 12,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 26.0,
    "lastPrimaryQty": 12.0,
    "lastSecondaryQty": 14.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 3,
    "lowThreshold": 9,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 3,
    "active": true
  },
  {
    "id": "passion-fruit-jam-selai-markisa",
    "name": "Passion Fruit Jam/Selai Markisa",
    "unit": "Bags",
    "cartonSize": 12,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 12.0,
    "lastPrimaryQty": 12.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 3,
    "lowThreshold": 9,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 3,
    "active": true
  },
  {
    "id": "apple-jam",
    "name": "Apple Jam",
    "unit": "Bags",
    "cartonSize": 24,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 0.0,
    "lastPrimaryQty": 0.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 6,
    "lowThreshold": 18,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 6,
    "active": false
  },
  {
    "id": "chocolate-sauce",
    "name": "Chocolate Sauce",
    "unit": "Bags",
    "cartonSize": 6,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 6.0,
    "lastPrimaryQty": 6.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 2,
    "lowThreshold": 4,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 2,
    "active": true
  },
  {
    "id": "grape-juice",
    "name": "Grape Juice",
    "unit": "PCS",
    "cartonSize": 12,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 1.0,
    "lastPrimaryQty": 1.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 25,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "sundae-cup",
    "name": "Sundae Cup",
    "unit": "PCS",
    "cartonSize": 1000,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 624.0,
    "lastPrimaryQty": 500.0,
    "lastSecondaryQty": 124.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 100,
    "lowThreshold": 300,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 100,
    "active": true
  },
  {
    "id": "peach-oolong-milktea-cup",
    "name": "Peach Oolong Milktea Cup",
    "unit": "PCS",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 869.0,
    "lastPrimaryQty": 500.0,
    "lastSecondaryQty": 369.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "signature-earl-grey-cup",
    "name": "Signature Earl Grey Cup",
    "unit": "PCS",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 912.0,
    "lastPrimaryQty": 500.0,
    "lastSecondaryQty": 412.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "jasmine-milktea-cup",
    "name": "Jasmine Milktea Cup",
    "unit": "PCS",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 801.0,
    "lastPrimaryQty": 500.0,
    "lastSecondaryQty": 301.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "da-hong-pao-cup",
    "name": "Da Hong Pao Cup",
    "unit": "PCS",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 2591.0,
    "lastPrimaryQty": 2000.0,
    "lastSecondaryQty": 591.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "plastic-cup-90-610-large",
    "name": "Plastic Cup 90-610 Large",
    "unit": "PCS",
    "cartonSize": 1000,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 258.0,
    "lastPrimaryQty": 0.0,
    "lastSecondaryQty": 258.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 100,
    "lowThreshold": 300,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 100,
    "active": true
  },
  {
    "id": "plastic-cup-90-500-small",
    "name": "Plastic Cup 90-500 Small",
    "unit": "PCS",
    "cartonSize": 1000,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 669.0,
    "lastPrimaryQty": 0.0,
    "lastSecondaryQty": 669.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 100,
    "lowThreshold": 300,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 100,
    "active": true
  },
  {
    "id": "shake-cup",
    "name": "Shake Cup",
    "unit": "PCS",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 321.0,
    "lastPrimaryQty": 321.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "shake-cup-cover",
    "name": "Shake Cup Cover",
    "unit": "PCS",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 324.0,
    "lastPrimaryQty": 324.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "bucket-cup",
    "name": "Bucket Cup",
    "unit": "PCS",
    "cartonSize": 300,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 236.0,
    "lastPrimaryQty": 236.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 30,
    "lowThreshold": 90,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 30,
    "active": true
  },
  {
    "id": "bucket-cup-cover",
    "name": "Bucket Cup Cover",
    "unit": "PCS",
    "cartonSize": 300,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 236.0,
    "lastPrimaryQty": 236.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 30,
    "lowThreshold": 90,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 30,
    "active": true
  },
  {
    "id": "cup-lid-black",
    "name": "Cup Lid ( Black )",
    "unit": "PCS",
    "cartonSize": 1000,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 11171.0,
    "lastPrimaryQty": 10000.0,
    "lastSecondaryQty": 1171.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 100,
    "lowThreshold": 300,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 100,
    "active": true
  },
  {
    "id": "dome-cup-lid",
    "name": "Dome Cup Lid",
    "unit": "PCS",
    "cartonSize": 2000,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 2114.0,
    "lastPrimaryQty": 2000.0,
    "lastSecondaryQty": 114.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 200,
    "lowThreshold": 600,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 200,
    "active": true
  },
  {
    "id": "apple-cup",
    "name": "Apple Cup",
    "unit": "Bags",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Packaging",
    "currentQty": 0.0,
    "lastPrimaryQty": 0.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 125,
    "lowThreshold": 375,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 125,
    "active": false
  },
  {
    "id": "apple-cup-cover",
    "name": "Apple Cup Cover",
    "unit": "Bags",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Packaging",
    "currentQty": 0.0,
    "lastPrimaryQty": 0.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 125,
    "lowThreshold": 375,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 125,
    "active": false
  },
  {
    "id": "soda-water",
    "name": "Soda Water",
    "unit": "Bags",
    "cartonSize": 50,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Gudang 2",
    "category": "Bahan",
    "currentQty": 0.0,
    "lastPrimaryQty": 0.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 12,
    "lowThreshold": 38,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 12,
    "active": false
  },
  {
    "id": "take-a-way-bag-small",
    "name": "Take a Way Bag Small",
    "unit": "PCS",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 298.0,
    "lastPrimaryQty": 248.0,
    "lastSecondaryQty": 50.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "take-a-way-bag-big",
    "name": "Take a Way Bag Big",
    "unit": "PCS",
    "cartonSize": 500,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 563.0,
    "lastPrimaryQty": 450.0,
    "lastSecondaryQty": 113.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 50,
    "lowThreshold": 150,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 50,
    "active": true
  },
  {
    "id": "sedotan-kuning",
    "name": "Sedotan Kuning",
    "unit": "PCS",
    "cartonSize": 3000,
    "primaryLocation": "Gudang Istirahat",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 300.0,
    "lastPrimaryQty": 2050.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 300,
    "lowThreshold": 900,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 300,
    "active": true
  },
  {
    "id": "sedotan-besar",
    "name": "Sedotan Besar",
    "unit": "PCS",
    "cartonSize": 4000,
    "primaryLocation": "Gudang Istirahat",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 1988.0,
    "lastPrimaryQty": 1988.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 400,
    "lowThreshold": 1200,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 400,
    "active": true
  },
  {
    "id": "sedotan-sedang",
    "name": "Sedotan Sedang",
    "unit": "PCS",
    "cartonSize": 6000,
    "primaryLocation": "Gudang Istirahat",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 6005.0,
    "lastPrimaryQty": 6005.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 600,
    "lowThreshold": 1800,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 600,
    "active": true
  },
  {
    "id": "plastik-sealer",
    "name": "Plastik Sealer",
    "unit": "Rolls",
    "cartonSize": 6,
    "primaryLocation": "Gudang Istirahat",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 5.0,
    "lastPrimaryQty": 5.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 2,
    "lowThreshold": 4,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 2,
    "active": true
  },
  {
    "id": "kertas-print-orderan",
    "name": "Kertas Print Orderan",
    "unit": "PCS",
    "cartonSize": 100,
    "primaryLocation": "Gudang Istirahat",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 90.0,
    "lastPrimaryQty": 80.0,
    "lastSecondaryQty": 10.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 30,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "kertas-print-thermal",
    "name": "Kertas Print Thermal",
    "unit": "PCS",
    "cartonSize": 100,
    "primaryLocation": "Gudang Istirahat",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 283.0,
    "lastPrimaryQty": 200.0,
    "lastSecondaryQty": 83.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 30,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "single-cup-bag",
    "name": "Single Cup Bag",
    "unit": "PCS",
    "cartonSize": 5000,
    "primaryLocation": "Gudang Istirahat",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 4700.0,
    "lastPrimaryQty": 4700.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 500,
    "lowThreshold": 1500,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 500,
    "active": true
  },
  {
    "id": "big-cup-bag",
    "name": "Big Cup Bag",
    "unit": "PCS",
    "cartonSize": 1000,
    "primaryLocation": "Gudang Istirahat",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 2000.0,
    "lastPrimaryQty": 2000.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 100,
    "lowThreshold": 300,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 100,
    "active": true
  },
  {
    "id": "spoon-plastic",
    "name": "Spoon Plastic",
    "unit": "PCS",
    "cartonSize": 1000,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 3035.0,
    "lastPrimaryQty": 2000.0,
    "lastSecondaryQty": 1035.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 100,
    "lowThreshold": 300,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 100,
    "active": true
  },
  {
    "id": "tisu-kecil",
    "name": "Tisu Kecil",
    "unit": "PCS",
    "cartonSize": 60,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 12.0,
    "lastPrimaryQty": 12.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 25,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "tisu-besar",
    "name": "Tisu Besar",
    "unit": "PCS",
    "cartonSize": 20,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 19.0,
    "lastPrimaryQty": 19.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 25,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "papper-bag-dahongpau",
    "name": "Papper Bag Dahongpau",
    "unit": "PCS",
    "cartonSize": 0,
    "primaryLocation": "Gudang Utama",
    "secondaryLocation": "Bar",
    "category": "Packaging",
    "currentQty": 0.0,
    "lastPrimaryQty": 0.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-25",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 30,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "lemon",
    "name": "Lemon",
    "unit": "PCS",
    "cartonSize": 0,
    "primaryLocation": "Kitchen",
    "secondaryLocation": "Kitchen",
    "category": "Bahan",
    "currentQty": 29.0,
    "lastPrimaryQty": 29.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 30,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "sunkist",
    "name": "Sunkist",
    "unit": "PCS",
    "cartonSize": 0,
    "primaryLocation": "Kitchen",
    "secondaryLocation": "Kitchen",
    "category": "Fresh",
    "currentQty": 3.0,
    "lastPrimaryQty": 3.0,
    "lastSecondaryQty": 0.0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 30,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  },
  {
    "id": "semangka",
    "name": "Semangka",
    "unit": "PCS",
    "cartonSize": 0,
    "primaryLocation": "Kitchen",
    "secondaryLocation": "Kitchen",
    "category": "Fresh",
    "currentQty": 1.0,
    "lastPrimaryQty": 1.0,
    "lastSecondaryQty": 0,
    "lastOpnameDate": "2026-08-31",
    "criticalItem": false,
    "criticalThreshold": 10,
    "lowThreshold": 30,
    "leadTimeDays": 2,
    "targetCoverageDays": 7,
    "safetyStock": 10,
    "active": true
  }
];
export const STOCK_REFERENCE_SNAPSHOTS = [
  {
    "date": "2026-08-09",
    "itemId": "milktea-powder",
    "name": "Milktea Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 80.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 4.0,
    "totalQty": 84.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "ice-cream-yoghurt",
    "name": "Ice Cream Yoghurt",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 24.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 1.0,
    "totalQty": 25.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "ice-cream-original",
    "name": "Ice Cream Original",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 24.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 3.0,
    "totalQty": 27.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "peach-flavor-oolong-tea",
    "name": "Peach Flavor Oolong Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 200.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 74.0,
    "totalQty": 274.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "black-tea-putih",
    "name": "Black Tea Putih",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 1.0,
    "unit": "Pack"
  },
  {
    "date": "2026-08-09",
    "itemId": "black-tea",
    "name": "Black Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 200.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 199.0,
    "totalQty": 399.0,
    "unit": "Pack"
  },
  {
    "date": "2026-08-09",
    "itemId": "jasmine-green-tea-blooming",
    "name": "Jasmine Green Tea / Blooming",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 60.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 62.0,
    "totalQty": 122.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "green-tea",
    "name": "Green Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 73.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 6.0,
    "totalQty": 79.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "green-tea-kemasan-hijau",
    "name": "Green Tea Kemasan Hijau",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 50.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 50.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "da-hong-pao-tea",
    "name": "Da Hong Pao Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 175.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 175.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "lemon-powder",
    "name": "Lemon Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1.0,
    "secondaryLocation": "Kitchen",
    "secondaryQty": 0.0,
    "totalQty": 1.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "sugar-syrup",
    "name": "Sugar Syrup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 60.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 2.0,
    "totalQty": 62.0,
    "unit": "Barels"
  },
  {
    "date": "2026-08-09",
    "itemId": "ice-cream-corn",
    "name": "Ice Cream Corn",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "tapioca-pearl-boba",
    "name": "Tapioca Pearl/Boba",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 5.0,
    "totalQty": 5.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "popping-boba",
    "name": "Popping Boba",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 9.0,
    "totalQty": 9.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "coffe-powder",
    "name": "Coffe Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 23.0,
    "totalQty": 23.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "caramel-pudding",
    "name": "Caramel Pudding",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 6.0,
    "totalQty": 6.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "jelly-powder",
    "name": "Jelly Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 4.0,
    "totalQty": 4.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "taffe-syrup",
    "name": "Taffe Syrup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 3.0,
    "totalQty": 3.0,
    "unit": "Barels"
  },
  {
    "date": "2026-08-09",
    "itemId": "cookies-crumble",
    "name": "Cookies Crumble",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 6.0,
    "totalQty": 6.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "nata-de-coco-coconut-jelly",
    "name": "Nata De Coco/Coconut Jelly",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 9.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 7.0,
    "totalQty": 16.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "peach-jam",
    "name": "Peach Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 18.0,
    "totalQty": 18.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "strawberry-jam",
    "name": "Strawberry Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 9.0,
    "totalQty": 9.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "manggo-jam",
    "name": "Manggo Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 12.0,
    "totalQty": 24.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "passion-fruit-jam-selai-markisa",
    "name": "Passion Fruit Jam/Selai Markisa",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 4.0,
    "totalQty": 4.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "apple-jam",
    "name": "Apple Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "chocolate-sauce",
    "name": "Chocolate Sauce",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 1.0,
    "totalQty": 13.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "grape-juice",
    "name": "Grape Juice",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 6.0,
    "totalQty": 6.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "sundae-cup",
    "name": "Sundae Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 927.0,
    "totalQty": 1927.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "peach-oolong-milktea-cup",
    "name": "Peach Oolong Milktea Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 587.0,
    "totalQty": 2087.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "signature-earl-grey-cup",
    "name": "Signature Earl Grey Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 506.0,
    "totalQty": 2006.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "jasmine-milktea-cup",
    "name": "Jasmine Milktea Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 542.0,
    "totalQty": 1042.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "da-hong-pao-cup",
    "name": "Da Hong Pao Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 302.0,
    "totalQty": 1302.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "plastic-cup-90-610-large",
    "name": "Plastic Cup 90-610 Large",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 257.0,
    "totalQty": 2257.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "plastic-cup-90-500-small",
    "name": "Plastic Cup 90-500 Small",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 108.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 21.0,
    "totalQty": 129.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "shake-cup",
    "name": "Shake Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 80.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 63.0,
    "totalQty": 143.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "shake-cup-cover",
    "name": "Shake Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 146.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 146.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "bucket-cup",
    "name": "Bucket Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "bucket-cup-cover",
    "name": "Bucket Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "cup-lid-black",
    "name": "Cup Lid ( Black )",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 3000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 700.0,
    "totalQty": 3700.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "dome-cup-lid",
    "name": "Dome Cup Lid",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 313.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 313.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "apple-cup",
    "name": "Apple Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "apple-cup-cover",
    "name": "Apple Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "soda-water",
    "name": "Soda Water",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-09",
    "itemId": "take-a-way-bag-small",
    "name": "Take a Way Bag Small",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 470.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 470.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "take-a-way-bag-big",
    "name": "Take a Way Bag Big",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 297.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 297.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "sedotan-kuning",
    "name": "Sedotan Kuning",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 1923.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 1923.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "sedotan-besar",
    "name": "Sedotan Besar",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 3600.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 186.0,
    "totalQty": 3786.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "sedotan-sedang",
    "name": "Sedotan Sedang",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 1300.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 357.0,
    "totalQty": 1657.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "plastik-sealer",
    "name": "Plastik Sealer",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 6.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 6.0,
    "unit": "Rolls"
  },
  {
    "date": "2026-08-09",
    "itemId": "kertas-print-orderan",
    "name": "Kertas Print Orderan",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 5.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 3.0,
    "totalQty": 8.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "kertas-print-thermal",
    "name": "Kertas Print Thermal",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 140.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 2.0,
    "totalQty": 142.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "single-cup-bag",
    "name": "Single Cup Bag",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 8.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 8.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "big-cup-bag",
    "name": "Big Cup Bag",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 700.0,
    "totalQty": 1700.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "spoon-plastic",
    "name": "Spoon Plastic",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 502.0,
    "totalQty": 2502.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "tisu-kecil",
    "name": "Tisu Kecil",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 52.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 52.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-09",
    "itemId": "tisu-besar",
    "name": "Tisu Besar",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 14.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 14.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "milktea-powder",
    "name": "Milktea Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 10.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 5.0,
    "totalQty": 15.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "ice-cream-yoghurt",
    "name": "Ice Cream Yoghurt",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 7.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 7.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "ice-cream-original",
    "name": "Ice Cream Original",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 10.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 10.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "peach-flavor-oolong-tea",
    "name": "Peach Flavor Oolong Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 143.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 143.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "black-tea-putih",
    "name": "Black Tea Putih",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 1.0,
    "unit": "Pack"
  },
  {
    "date": "2026-08-18",
    "itemId": "black-tea",
    "name": "Black Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 200.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 118.0,
    "totalQty": 318.0,
    "unit": "Pack"
  },
  {
    "date": "2026-08-18",
    "itemId": "jasmine-green-tea-blooming",
    "name": "Jasmine Green Tea / Blooming",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 120.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 29.0,
    "totalQty": 149.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "green-tea",
    "name": "Green Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 5.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 5.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "green-tea-kemasan-hijau",
    "name": "Green Tea Kemasan Hijau",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 50.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 50.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "da-hong-pao-tea",
    "name": "Da Hong Pao Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 160.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 160.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "lemon-powder",
    "name": "Lemon Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Kitchen",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "sugar-syrup",
    "name": "Sugar Syrup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 24.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 11.0,
    "totalQty": 35.0,
    "unit": "Barels"
  },
  {
    "date": "2026-08-18",
    "itemId": "ice-cream-corn",
    "name": "Ice Cream Corn",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 220.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 105.0,
    "totalQty": 325.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "tapioca-pearl-boba",
    "name": "Tapioca Pearl/Boba",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 13.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 13.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "popping-boba",
    "name": "Popping Boba",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 4.0,
    "totalQty": 16.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "coffe-powder",
    "name": "Coffe Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 21.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 21.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "caramel-pudding",
    "name": "Caramel Pudding",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "jelly-powder",
    "name": "Jelly Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 3.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 3.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "taffe-syrup",
    "name": "Taffe Syrup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 2.0,
    "unit": "Barels"
  },
  {
    "date": "2026-08-18",
    "itemId": "cookies-crumble",
    "name": "Cookies Crumble",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 22.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 22.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "nata-de-coco-coconut-jelly",
    "name": "Nata De Coco/Coconut Jelly",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 9.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 13.0,
    "totalQty": 22.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "peach-jam",
    "name": "Peach Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 15.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 15.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "strawberry-jam",
    "name": "Strawberry Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 2.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "manggo-jam",
    "name": "Manggo Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 5.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 5.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "passion-fruit-jam-selai-markisa",
    "name": "Passion Fruit Jam/Selai Markisa",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 10.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 10.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "apple-jam",
    "name": "Apple Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "chocolate-sauce",
    "name": "Chocolate Sauce",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 2.0,
    "totalQty": 14.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "grape-juice",
    "name": "Grape Juice",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 4.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 4.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "sundae-cup",
    "name": "Sundae Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 408.0,
    "totalQty": 1408.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "peach-oolong-milktea-cup",
    "name": "Peach Oolong Milktea Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 590.0,
    "totalQty": 2090.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "signature-earl-grey-cup",
    "name": "Signature Earl Grey Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 285.0,
    "totalQty": 1285.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "jasmine-milktea-cup",
    "name": "Jasmine Milktea Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 225.0,
    "totalQty": 1225.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "da-hong-pao-cup",
    "name": "Da Hong Pao Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 14.0,
    "totalQty": 1014.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "plastic-cup-90-610-large",
    "name": "Plastic Cup 90-610 Large",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 440.0,
    "totalQty": 1440.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "plastic-cup-90-500-small",
    "name": "Plastic Cup 90-500 Small",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 956.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 956.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "shake-cup",
    "name": "Shake Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 496.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 496.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "shake-cup-cover",
    "name": "Shake Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 530.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 530.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "bucket-cup",
    "name": "Bucket Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 271.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 271.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "bucket-cup-cover",
    "name": "Bucket Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 271.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 271.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "cup-lid-black",
    "name": "Cup Lid ( Black )",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 8.0,
    "totalQty": 1008.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "dome-cup-lid",
    "name": "Dome Cup Lid",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 233.0,
    "totalQty": 2233.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "apple-cup",
    "name": "Apple Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "apple-cup-cover",
    "name": "Apple Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "soda-water",
    "name": "Soda Water",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-18",
    "itemId": "take-a-way-bag-small",
    "name": "Take a Way Bag Small",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 178.0,
    "totalQty": 678.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "take-a-way-bag-big",
    "name": "Take a Way Bag Big",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 100.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 86.0,
    "totalQty": 186.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "sedotan-kuning",
    "name": "Sedotan Kuning",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 270.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 300.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "sedotan-besar",
    "name": "Sedotan Besar",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 2900.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 371.0,
    "totalQty": 3271.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "sedotan-sedang",
    "name": "Sedotan Sedang",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 600.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 595.0,
    "totalQty": 1195.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "plastik-sealer",
    "name": "Plastik Sealer",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 3.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 3.0,
    "unit": "Rolls"
  },
  {
    "date": "2026-08-18",
    "itemId": "kertas-print-orderan",
    "name": "Kertas Print Orderan",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 2.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 2.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "kertas-print-thermal",
    "name": "Kertas Print Thermal",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 60.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 13.0,
    "totalQty": 73.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "single-cup-bag",
    "name": "Single Cup Bag",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 1000.0,
    "totalQty": 2000.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "big-cup-bag",
    "name": "Big Cup Bag",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 400.0,
    "totalQty": 1400.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "spoon-plastic",
    "name": "Spoon Plastic",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 800.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 73.0,
    "totalQty": 873.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "tisu-kecil",
    "name": "Tisu Kecil",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 38.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 38.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "tisu-besar",
    "name": "Tisu Besar",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 4.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 4.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-18",
    "itemId": "papper-bag-dahongpau",
    "name": "Papper Bag Dahongpau",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 74.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 74.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "milktea-powder",
    "name": "Milktea Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 10.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 8.0,
    "totalQty": 18.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "ice-cream-yoghurt",
    "name": "Ice Cream Yoghurt",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 8.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 7.0,
    "totalQty": 15.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "ice-cream-original",
    "name": "Ice Cream Original",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 8.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 9.0,
    "totalQty": 17.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "peach-flavor-oolong-tea",
    "name": "Peach Flavor Oolong Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 200.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 29.0,
    "totalQty": 229.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "black-tea-putih",
    "name": "Black Tea Putih",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 1.0,
    "unit": "Pack"
  },
  {
    "date": "2026-08-25",
    "itemId": "black-tea",
    "name": "Black Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 200.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 39.0,
    "totalQty": 239.0,
    "unit": "Pack"
  },
  {
    "date": "2026-08-25",
    "itemId": "jasmine-green-tea-blooming",
    "name": "Jasmine Green Tea / Blooming",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 60.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 65.0,
    "totalQty": 125.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "green-tea",
    "name": "Green Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "green-tea-kemasan-hijau",
    "name": "Green Tea Kemasan Hijau",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 8.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 8.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "da-hong-pao-tea",
    "name": "Da Hong Pao Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 230.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 230.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "lemon-powder",
    "name": "Lemon Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2.0,
    "secondaryLocation": "Kitchen",
    "secondaryQty": 0.0,
    "totalQty": 2.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "sugar-syrup",
    "name": "Sugar Syrup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 40.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 2.0,
    "totalQty": 42.0,
    "unit": "Barels"
  },
  {
    "date": "2026-08-25",
    "itemId": "ice-cream-corn",
    "name": "Ice Cream Corn",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2400.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 93.0,
    "totalQty": 2493.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "tapioca-pearl-boba",
    "name": "Tapioca Pearl/Boba",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 16.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 8.0,
    "totalQty": 24.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "popping-boba",
    "name": "Popping Boba",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 12.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "coffe-powder",
    "name": "Coffe Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 19.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 19.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "caramel-pudding",
    "name": "Caramel Pudding",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 14.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 14.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "jelly-powder",
    "name": "Jelly Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 8.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 2.0,
    "totalQty": 10.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "taffe-syrup",
    "name": "Taffe Syrup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 8.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 8.0,
    "unit": "Barels"
  },
  {
    "date": "2026-08-25",
    "itemId": "cookies-crumble",
    "name": "Cookies Crumble",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 15.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 15.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "nata-de-coco-coconut-jelly",
    "name": "Nata De Coco/Coconut Jelly",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 9.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 10.0,
    "totalQty": 19.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "peach-jam",
    "name": "Peach Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 13.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 13.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "strawberry-jam",
    "name": "Strawberry Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 13.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 13.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "manggo-jam",
    "name": "Manggo Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 36.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 2.0,
    "totalQty": 38.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "passion-fruit-jam-selai-markisa",
    "name": "Passion Fruit Jam/Selai Markisa",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 4.0,
    "totalQty": 16.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "apple-jam",
    "name": "Apple Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "chocolate-sauce",
    "name": "Chocolate Sauce",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 6.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 3.0,
    "totalQty": 9.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "grape-juice",
    "name": "Grape Juice",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 3.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 3.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "sundae-cup",
    "name": "Sundae Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 370.0,
    "totalQty": 1370.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "peach-oolong-milktea-cup",
    "name": "Peach Oolong Milktea Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 543.0,
    "totalQty": 1043.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "signature-earl-grey-cup",
    "name": "Signature Earl Grey Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 385.0,
    "totalQty": 1385.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "jasmine-milktea-cup",
    "name": "Jasmine Milktea Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 756.0,
    "totalQty": 1756.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "da-hong-pao-cup",
    "name": "Da Hong Pao Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 421.0,
    "totalQty": 1921.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "plastic-cup-90-610-large",
    "name": "Plastic Cup 90-610 Large",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 739.0,
    "totalQty": 1739.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "plastic-cup-90-500-small",
    "name": "Plastic Cup 90-500 Small",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 820.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 820.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "shake-cup",
    "name": "Shake Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 414.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 414.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "shake-cup-cover",
    "name": "Shake Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 417.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 417.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "bucket-cup",
    "name": "Bucket Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 253.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 253.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "bucket-cup-cover",
    "name": "Bucket Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 253.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 253.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "cup-lid-black",
    "name": "Cup Lid ( Black )",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 3000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 931.0,
    "totalQty": 3931.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "dome-cup-lid",
    "name": "Dome Cup Lid",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 162.0,
    "totalQty": 2162.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "apple-cup",
    "name": "Apple Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "apple-cup-cover",
    "name": "Apple Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "soda-water",
    "name": "Soda Water",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-25",
    "itemId": "take-a-way-bag-small",
    "name": "Take a Way Bag Small",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 450.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 25.0,
    "totalQty": 475.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "take-a-way-bag-big",
    "name": "Take a Way Bag Big",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 113.0,
    "totalQty": 613.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "sedotan-kuning",
    "name": "Sedotan Kuning",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 900.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 203.0,
    "totalQty": 300.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "sedotan-besar",
    "name": "Sedotan Besar",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 185.0,
    "totalQty": 2185.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "sedotan-sedang",
    "name": "Sedotan Sedang",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 311.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 311.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "plastik-sealer",
    "name": "Plastik Sealer",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 6.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 1.0,
    "totalQty": 7.0,
    "unit": "Rolls"
  },
  {
    "date": "2026-08-25",
    "itemId": "kertas-print-orderan",
    "name": "Kertas Print Orderan",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 105.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 105.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "kertas-print-thermal",
    "name": "Kertas Print Thermal",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 300.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 23.0,
    "totalQty": 323.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "single-cup-bag",
    "name": "Single Cup Bag",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 1250.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 1250.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "big-cup-bag",
    "name": "Big Cup Bag",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 500.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "spoon-plastic",
    "name": "Spoon Plastic",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 565.0,
    "totalQty": 1565.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "tisu-kecil",
    "name": "Tisu Kecil",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 22.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 22.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "tisu-besar",
    "name": "Tisu Besar",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-25",
    "itemId": "papper-bag-dahongpau",
    "name": "Papper Bag Dahongpau",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "milktea-powder",
    "name": "Milktea Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 20.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 21.0,
    "totalQty": 41.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "ice-cream-yoghurt",
    "name": "Ice Cream Yoghurt",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 11.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 3.0,
    "totalQty": 14.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "ice-cream-original",
    "name": "Ice Cream Original",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 3.0,
    "totalQty": 5.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "peach-flavor-oolong-tea",
    "name": "Peach Flavor Oolong Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 136.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 136.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "black-tea-putih",
    "name": "Black Tea Putih",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 1.0,
    "unit": "Pack"
  },
  {
    "date": "2026-08-31",
    "itemId": "black-tea",
    "name": "Black Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 205.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 205.0,
    "unit": "Pack"
  },
  {
    "date": "2026-08-31",
    "itemId": "jasmine-green-tea-blooming",
    "name": "Jasmine Green Tea / Blooming",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 60.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 39.0,
    "totalQty": 99.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "green-tea",
    "name": "Green Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "green-tea-kemasan-hijau",
    "name": "Green Tea Kemasan Hijau",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 13.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 1.0,
    "totalQty": 14.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "da-hong-pao-tea",
    "name": "Da Hong Pao Tea",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 200.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 98.0,
    "totalQty": 298.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "lemon-powder",
    "name": "Lemon Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1.0,
    "secondaryLocation": "Kitchen",
    "secondaryQty": 0.0,
    "totalQty": 1.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "sugar-syrup",
    "name": "Sugar Syrup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 48.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 8.0,
    "totalQty": 56.0,
    "unit": "Barels"
  },
  {
    "date": "2026-08-31",
    "itemId": "ice-cream-corn",
    "name": "Ice Cream Corn",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1600.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 173.0,
    "totalQty": 1773.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "tapioca-pearl-boba",
    "name": "Tapioca Pearl/Boba",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 16.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 4.0,
    "totalQty": 20.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "popping-boba",
    "name": "Popping Boba",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 9.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 9.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "coffe-powder",
    "name": "Coffe Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 17.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 17.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "caramel-pudding",
    "name": "Caramel Pudding",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 9.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 9.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "jelly-powder",
    "name": "Jelly Powder",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 8.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 2.0,
    "totalQty": 10.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "taffe-syrup",
    "name": "Taffe Syrup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 8.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 8.0,
    "unit": "Barels"
  },
  {
    "date": "2026-08-31",
    "itemId": "cookies-crumble",
    "name": "Cookies Crumble",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 10.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 10.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "nata-de-coco-coconut-jelly",
    "name": "Nata De Coco/Coconut Jelly",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 9.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 9.0,
    "totalQty": 18.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "peach-jam",
    "name": "Peach Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 11.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 11.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "strawberry-jam",
    "name": "Strawberry Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 11.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 11.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "manggo-jam",
    "name": "Manggo Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 14.0,
    "totalQty": 26.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "passion-fruit-jam-selai-markisa",
    "name": "Passion Fruit Jam/Selai Markisa",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 12.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "apple-jam",
    "name": "Apple Jam",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "chocolate-sauce",
    "name": "Chocolate Sauce",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 6.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 6.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "grape-juice",
    "name": "Grape Juice",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 1.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 1.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "sundae-cup",
    "name": "Sundae Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 124.0,
    "totalQty": 624.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "peach-oolong-milktea-cup",
    "name": "Peach Oolong Milktea Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 369.0,
    "totalQty": 869.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "signature-earl-grey-cup",
    "name": "Signature Earl Grey Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 412.0,
    "totalQty": 912.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "jasmine-milktea-cup",
    "name": "Jasmine Milktea Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 500.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 301.0,
    "totalQty": 801.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "da-hong-pao-cup",
    "name": "Da Hong Pao Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 591.0,
    "totalQty": 2591.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "plastic-cup-90-610-large",
    "name": "Plastic Cup 90-610 Large",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 258.0,
    "totalQty": 258.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "plastic-cup-90-500-small",
    "name": "Plastic Cup 90-500 Small",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 669.0,
    "totalQty": 669.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "shake-cup",
    "name": "Shake Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 321.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 321.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "shake-cup-cover",
    "name": "Shake Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 324.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 324.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "bucket-cup",
    "name": "Bucket Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 236.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 236.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "bucket-cup-cover",
    "name": "Bucket Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 236.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 236.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "cup-lid-black",
    "name": "Cup Lid ( Black )",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 10000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 1171.0,
    "totalQty": 11171.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "dome-cup-lid",
    "name": "Dome Cup Lid",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 114.0,
    "totalQty": 2114.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "apple-cup",
    "name": "Apple Cup",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "apple-cup-cover",
    "name": "Apple Cup Cover",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "soda-water",
    "name": "Soda Water",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 0.0,
    "secondaryLocation": "Gudang 2",
    "secondaryQty": 0.0,
    "totalQty": 0.0,
    "unit": "Bags"
  },
  {
    "date": "2026-08-31",
    "itemId": "take-a-way-bag-small",
    "name": "Take a Way Bag Small",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 248.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 50.0,
    "totalQty": 298.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "take-a-way-bag-big",
    "name": "Take a Way Bag Big",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 450.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 113.0,
    "totalQty": 563.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "sedotan-kuning",
    "name": "Sedotan Kuning",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 2050.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 300.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "sedotan-besar",
    "name": "Sedotan Besar",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 1988.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 1988.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "sedotan-sedang",
    "name": "Sedotan Sedang",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 6005.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 6005.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "plastik-sealer",
    "name": "Plastik Sealer",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 5.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 5.0,
    "unit": "Rolls"
  },
  {
    "date": "2026-08-31",
    "itemId": "kertas-print-orderan",
    "name": "Kertas Print Orderan",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 80.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 10.0,
    "totalQty": 90.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "kertas-print-thermal",
    "name": "Kertas Print Thermal",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 200.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 83.0,
    "totalQty": 283.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "single-cup-bag",
    "name": "Single Cup Bag",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 4700.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 4700.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "big-cup-bag",
    "name": "Big Cup Bag",
    "primaryLocation": "Gudang Istirahat",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 2000.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "spoon-plastic",
    "name": "Spoon Plastic",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 2000.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 1035.0,
    "totalQty": 3035.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "tisu-kecil",
    "name": "Tisu Kecil",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 12.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 12.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "tisu-besar",
    "name": "Tisu Besar",
    "primaryLocation": "Gudang Utama",
    "primaryQty": 19.0,
    "secondaryLocation": "Bar",
    "secondaryQty": 0.0,
    "totalQty": 19.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "lemon",
    "name": "Lemon",
    "primaryLocation": "Kitchen",
    "primaryQty": 29.0,
    "secondaryLocation": "Kitchen",
    "secondaryQty": 0.0,
    "totalQty": 29.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "sunkist",
    "name": "Sunkist",
    "primaryLocation": "Kitchen",
    "primaryQty": 3.0,
    "secondaryLocation": "Kitchen",
    "secondaryQty": 0.0,
    "totalQty": 3.0,
    "unit": "PCS"
  },
  {
    "date": "2026-08-31",
    "itemId": "semangka",
    "name": "Semangka",
    "primaryLocation": "Kitchen",
    "primaryQty": 1.0,
    "secondaryLocation": "Kitchen",
    "secondaryQty": 0,
    "totalQty": 1.0,
    "unit": "PCS"
  }
];
